export const texts = {
  app: {
    title: 'Super Tarifario PLUS',
    eyebrow: 'Agente operativo',
    resetDemo: 'Restaurar demo',
    logout: 'Cerrar sesión'
  },
  login: {
    title: 'Acceso cliente',
    subtitle: 'Entra con tu cliente y código para usar el tarifario asignado.',
    client: 'Cliente',
    code: 'Código',
    clientPlaceholder: 'Nombre de cliente',
    codePlaceholder: 'Código de acceso',
    submit: 'Entrar',
    error: 'Cliente o código no válido.',
    adminBadge: 'Administrador',
    lockedTariff: 'Tarifario asignado'
  },
  admin: {
    open: 'Administración',
    close: 'Cerrar administración',
    title: 'Administración de accesos',
    subtitle: 'Gestión local provisional de clientes, códigos y tarifarios asignados.',
    addUser: 'Añadir usuario',
    userName: 'Nombre',
    loginCode: 'Código cliente',
    pin: 'PIN',
    role: 'Rol',
    assignedTariff: 'Tarifario asignado',
    active: 'Activo',
    status: 'Estado',
    adminRole: 'Admin',
    clientRole: 'Cliente',
    allTariffs: 'Todos los tarifarios',
    activeStatus: 'Activo',
    inactiveStatus: 'Inactivo',
    save: 'Guardar cambios',
    saved: 'Cambios guardados.',
    saveError: 'No se pudieron guardar los cambios.',
    supabaseConnected: 'Conectado a Supabase.',
    localNotice: 'Cambios guardados en este navegador. Al conectar Supabase se guardarán en base de datos.'
  },
  fields: {
    context: 'Contexto',
    catalog: 'Tarifario',
    client: 'Cliente',
    currentTariff: 'Tarifario actual',
    sheet: 'Hoja',
    service: 'Servicio',
    code: 'Código',
    unit: 'Unidad',
    price: 'Precio unitario',
    minimum: 'Mínimo',
    notes: 'Notas',
    description: 'Descripción',
    contact: 'Contacto',
    zone: 'Zona',
    assistantInput: 'Instrucciones del cliente, correo o albarán',
    requiredData: 'Datos obligatorios para tarifar',
    integrationStatus: 'Estado de integraciones'
  },
  assistant: {
    question: '¿En qué servicio puedo ayudarte?',
    initialMessage: 'Escribe la petición o sube albaranes, correos o capturas. Yo extraigo direcciones, bultos, pesos y medidas.',
    placeholder: 'Pega aquí el email, albarán o instrucciones del cliente. También puedes subir documentos.',
    clientPlaceholder: 'Nombre del cliente',
    writeLabel: 'Mensaje para el agente',
    uploadDocument: 'Adjuntar archivos',
    uploadingDocument: 'Leyendo archivos',
    attachedDocuments: 'Documentos adjuntos',
    documentsAttached: '{count} archivo(s) adjuntado(s). Cuando pulses Analizar los cruzo con tus instrucciones.',
    attachedDocumentsFallback: 'Documentos adjuntos sin instrucciones escritas.',
    userInstructionsDocumentName: 'Instrucciones escritas del usuario',
    removeAttachedDocument: 'Quitar {name}',
    imageTextPending: 'Imagen pendiente de lectura OCR por IA.',
    documentAnalyzing: 'Analizando documentos para preparar la descripción del servicio.',
    documentReady: 'Documento analizado. Revisa la descripción antes de calcular.',
    documentsReady: '{count} documento(s) analizado(s). Revisa la descripción antes de calcular.',
    documentAiFallback: 'La IA no ha podido analizar el documento. Se aplica extraccion local estructurada.',
    documentRequiresAi: 'Para analizar documentos o imágenes con lógica real hace falta que OpenAI autentique correctamente.',
    documentSectionPrefix: 'Documento:',
    extractedData: 'Datos extraídos',
    instructions: 'Instrucciones detectadas',
    relevantTariffHints: 'Coincidencias del tarifario',
    tariffParameters: 'Parámetros para tarifar',
    tariffableFileTitle: 'Ficha tarifable extraída',
    status: 'Estado',
    serviceSummary: 'Resumen del servicio',
    serviceType: 'Tipo de servicio',
    duration: 'Duración',
    orderedRoute: 'Ruta ordenada',
    merchandise: 'Mercancía',
    maxSimultaneousLoad: 'Carga máxima simultánea',
    physicalPackages: 'Bultos físicos',
    packageMovements: 'Movimientos de bultos',
    estimatedWeight: 'Peso estimado',
    confirmedData: 'Datos confirmados',
    estimatedData: 'Datos estimados',
    contradictions: 'Contradicciones',
    cleanText: 'Texto limpio',
    noData: 'No informado',
    missingCriticalData: 'Datos faltantes para tarifa exacta',
    pickupAddresses: 'Direcciones de recogida',
    deliveryAddresses: 'Direcciones de entrega',
    stops: 'Paradas',
    packages: 'Bultos',
    totalPackages: 'Total bultos',
    weight: 'Peso',
    dimensions: 'Dimensiones',
    volume: 'Volumen',
    vehicleRequirements: 'Vehículo requerido',
    equipment: 'Medios solicitados',
    goods: 'Mercancía',
    date: 'Fecha',
    pickupWindows: 'Horarios de recogida',
    deliveryWindows: 'Horarios de entrega',
    contacts: 'Contactos',
    warnings: 'Avisos',
    agentTitle: 'Esto es lo que he entendido',
    agentUnderstood: 'Datos que usaré para tarifar',
    detectedCriteria: 'Criterios detectados por la IA',
    detectedHelper: 'Mozo/ayudante detectado',
    pendingHours: 'horas pendientes',
    agentMissing: 'Datos que faltan',
    agentNothingMissing: 'No veo datos críticos pendientes.',
    agentTariffMatch: 'Tarifas que revisaría',
    completeHere: 'Completar aquí',
    editableParameters: 'Parámetros editables para calcular',
    noEditableParameters: 'La IA no ha generado todavía una solicitud tarifable. Completa la descripción y vuelve a analizar.',
    parameterFamily: 'Familia',
    parameterOrigin: 'Origen',
    parameterDestination: 'Destino',
    parameterExtraStopAddresses: 'Direcciones de paradas extra',
    parameterExtraStopAddress: 'Parada extra',
    extraStopAddressPlaceholder: 'Dirección de parada intermedia',
    addExtraStopAddress: 'Añadir parada con dirección',
    removeExtraStopAddress: 'Quitar parada',
    parameterVehicle: 'Vehículo',
    parameterDistance: 'Km reales',
    calculateDistance: 'Calcular km',
    mapsDistanceSource: 'Distancia Google Maps',
    mapsRouteStops: 'Paradas consideradas para Google Maps',
    userConfirmedDistance: 'Distancia confirmada por usuario/Onus',
    userInstructionsApplied: 'Indicaciones escritas aplicadas',
    optimizedRoute: 'Ruta optimizada',
    routeUsedForDistance: 'Ruta usada para calcular km',
    mapsDistanceError: 'No se pudo calcular la distancia con Google Maps.',
    parameterWeight: 'Peso kg',
    parameterTemperature: 'Temperatura',
    parameterAdditionalStops: 'Paradas adicionales',
    parameterWaitHours: 'Espera facturable (h)',
    parameterMozoHours: 'Horas mozo',
    parameterMozoCount: 'Nº mozos',
    parameterMozoManualPrice: 'Importe mozo/ayudante (€)',
    parameterSchedule: 'Jornada',
    parameterVehicleSchedule: 'Jornada vehículo',
    parameterMozoSchedule: 'Jornada mozo',
    vehicleScheduleHelp: 'Define la duración que factura el vehículo.',
    mozoScheduleHelp: 'Define la duración del apoyo; rellena automáticamente las horas de mozo.',
    parameterLoadZone: 'Zona de carga',
    parameterDeliveryZone: 'Zona de reparto',
    parameterEstimatedStops: 'Paradas estimadas',
    parameterServiceDays: 'Cantidad de días',
    parameterStopAverage: 'Promedio por parada',
    lastMileEstimatorTitle: 'Cálculo estimado de última milla',
    lastMileEstimatorHelp: 'Calcula carga → zona de reparto → vuelta a origen y suma número de paradas × 0,3 km.',
    lastMileDistanceSource: 'Distancia estimada última milla',
    calculateLastMileDistance: 'Calcular última milla',
    parameterLiftPlatform: 'Plataforma',
    parameterRoundTrip: 'Ida y vuelta',
    parameterBatchedRoute: 'Ruta agrupada',
    parameterRouteOptimization: 'Optimizar orden',
    process: 'Analizar',
    processing: 'Analizando',
    approveAnalysis: 'Aprobar análisis',
    analysisApprovedShort: 'Análisis aprobado',
    tariff: 'Calcular tarifa',
    pricing: 'Calculando',
    thinkingDocuments: 'Leyendo documentos',
    thinkingAnalysis: 'Pensando con IA',
    thinkingPricing: 'Calculando tarifa',
    analysisTitle: 'Análisis de la petición',
    aiAnalyzing: 'Analizando con IA y cruzando contra el tarifario seleccionado.',
    analysisReady: 'Análisis preparado. Valida la propuesta antes de tarifar.',
    parametersChanged: 'Parámetros modificados. Aprueba de nuevo la propuesta antes de calcular.',
    catalogChanged: 'Tarifario cambiado. Conservo el análisis y los parámetros; vuelve a calcular la tarifa.',
    localAnalysisFallback: 'Análisis local estructurado aplicado porque el motor de IA no respondió.',
    aiUnavailable: 'La IA real no está disponible. Revisa la conexión con OpenAI antes de continuar.',
    apiUnavailable: 'No puedo conectar con el servicio local. Revisa que el backend esté levantado con npm run dev o npm run api.',
    analysisApproved: 'Análisis aprobado. Ya puedes tarifar con el tarifario seleccionado.',
    analysisRequired: 'Primero procesa y aprueba el análisis de la petición.',
    pricingUnavailable: 'No hay cálculo real disponible para esta petición. Revisa que la IA haya extraído familia, distancia/peso/bultos y parámetros suficientes antes de tarifar.',
    candidateServices: 'Servicios candidatos',
    requestData: 'Datos de la petición',
    assumptions: 'Supuestos',
    missingData: 'Datos faltantes',
    selectedTariff: 'Tarifario seleccionado',
    selectedClient: 'Cliente seleccionado',
    tariffCriterion: 'Criterio tarifario',
    pricingModel: 'Modelo de cálculo',
    calculationBreakdown: 'Desglose y operaciones',
    distanceCriterion: 'Criterio de distancia',
    minimumCriterion: 'Criterio de mínimos',
    prepareProposal: 'Enviar',
    voice: 'Grabar audio',
    voiceStop: 'Detener grabación',
    voiceListening: 'Escuchando. Habla y revisaré la transcripción en el cuadro de instrucciones.',
    voiceStopped: 'Grabación detenida. Revisa el texto antes de analizar.',
    voiceUnsupported: 'Este navegador no permite dictado por Web Speech API. Prueba con Chrome o Edge.',
    voicePermissionDenied: 'El navegador ha bloqueado el micrófono. Permite el acceso y vuelve a intentarlo.',
    voiceError: 'No he podido iniciar o mantener la grabación de voz.',
    proposalReady: 'He calculado una propuesta para {client} con el tarifario seleccionado.',
    quoteTitle: 'Tarifa detallada',
    quoteEmpty: 'No se ha generado una tarifa real todavía.',
    quantity: 'Cantidad',
    lineTotal: 'Total línea',
    quoteTotal: 'Total propuesta',
    sendQuote: 'Enviar presupuesto',
    sendProposal: 'Enviar propuesta',
    quoteDraftTitle: 'Preparar presupuesto',
    proposalDraftTitle: 'Preparar propuesta',
    quoteRecipient: 'Email destinatario',
    quoteRecipientPlaceholder: 'cliente@empresa.com',
    quoteSubject: 'Asunto',
    quoteMessage: 'Mensaje del presupuesto',
    proposalMessage: 'Mensaje de la propuesta',
    quotePreview: 'Vista previa',
    quoteCopy: 'Copiar texto',
    quoteOpenEmail: 'Abrir email',
    quoteClose: 'Cerrar',
    quoteCopied: 'Presupuesto copiado al portapapeles.',
    proposalCopied: 'Propuesta copiada al portapapeles.',
    quoteCopyError: 'No se pudo copiar automáticamente. Puedes seleccionar el texto manualmente.',
    quoteDefaultSubject: 'Presupuesto {tariff} - {client}',
    proposalDefaultSubject: 'Propuesta {tariff} - {client}',
    quoteGreeting: 'Hola,',
    quoteIntro: 'Te enviamos el presupuestosegún servicio solicitado.',
    proposalIntro: 'Enviamos propuesta según tarifas acordadas.',
    quoteValidity: 'Presupuesto sujeto a validación final de disponibilidad, horarios y datos operativos confirmados.',
    proposalValidity: 'Propuesta sujeta a validación final de disponibilidad, horarios y datos operativos confirmados.',
    quoteSignature: 'Un saludo,\nONUS Express'
  },
  imports: {
    analysisError: 'No se pudo extraer el documento automaticamente.'
  },
  system: {
    restored: 'Datos restaurados al estado inicial.',
    defaultUser: 'Admin',
    defaultClient: 'Cliente sin especificar',
    defaultUnit: 'Servicio',
    defaultCatalogDescription: 'Tarifas estándar para servicios principales',
    urgentCatalogDescription: 'Recargos y servicios para actuaciones prioritarias'
  }
} as const;
